package com.bing.mapper;

import com.bing.dto.StudentDto;
import com.bing.entity.Student;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * student
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * student
     *
     * @mbggenerated
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * student
     *
     * @mbggenerated
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * student
     *
     * @mbggenerated
     */
    Student selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * student
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * student
     *
     * @mbggenerated
     */

    int updateByPrimaryKey(Student record);

    /**
     * @Description 查询全部
     * @Author fzq
     * @Date 2017/12/12 20:28
     */
    public List<Student> queryAll();

    /**
     * @Description 根据id查询
     * @Author fzq
     * @Date 2017/12/12 20:27
     */
    public List<Student> findByid(Integer id);

    public List<Student> getAll();
    /**
     * @Description 根据id跟新
     * @Author fzq
     * @Date 2017/12/12 20:29
     */
    public int updateById(Student record);

    public int countRows();

    /**
     * @Description 实现分页
     * @Author fzq
     * @Date 2017/12/13 19:29
     */
    public List<Student> list(@Param("id") Integer id);

    /**
     * @Description 多表关联实现分页
     * @Author fzq
     * @Date 2017/12/13 19:29
     */
    List<StudentDto> findHobbies(@Param("id") Integer id);
}