package com.bing.mapper;

import com.bing.entity.User;

import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);

    /**
     * @Description 查询用户是否存在
     * @Author fzq
     * @Date 2017/12/20 19:17
     */
    public int findUser(@Param("user") String user);

    public int validate(@Param("user") String user, @Param("password") String password);
}