package com.bing.entity;

import java.util.Date;

public class FlBind {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_bind.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_bind.openid
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_bind.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_bind.fl_user_code
     *
     * @mbggenerated
     */
    private String flUserCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_bind.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_bind.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_bind.id
     *
     * @return the value of fl_bind.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_bind.id
     *
     * @param id the value for fl_bind.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_bind.openid
     *
     * @return the value of fl_bind.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_bind.openid
     *
     * @param openid the value for fl_bind.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_bind.nick_name
     *
     * @return the value of fl_bind.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_bind.nick_name
     *
     * @param nickName the value for fl_bind.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_bind.fl_user_code
     *
     * @return the value of fl_bind.fl_user_code
     *
     * @mbggenerated
     */
    public String getFlUserCode() {
        return flUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_bind.fl_user_code
     *
     * @param flUserCode the value for fl_bind.fl_user_code
     *
     * @mbggenerated
     */
    public void setFlUserCode(String flUserCode) {
        this.flUserCode = flUserCode == null ? null : flUserCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_bind.create_time
     *
     * @return the value of fl_bind.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_bind.create_time
     *
     * @param createTime the value for fl_bind.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_bind.update_time
     *
     * @return the value of fl_bind.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_bind.update_time
     *
     * @param updateTime the value for fl_bind.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}